### ISSUE TITLE
how can i use this to train a model with other language dataset?

### ISSUE THREAD

**Issue by loongriver** [IlyaGusev/summarus#1]

**Comment by IlyaGusev** [comment]
First, you need to write a reader for your dataset. You should inherit from SummarizationReader class.
Examples:
- RIA reader, json format https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/ria_reader.py
- Lenta reader, tsv format https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/lenta_reader.py
- CNN\Dailymail reader, some advanced format https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/cnn_dailymail_reader.py

Second, you should preprocess your dataset to obtain vocabulary. You can use https://github.com/IlyaGusev/summarus#preprocesspy to do this. It requires a configuration file with reader settings. For example, "reader" section from [this file](https://github.com/IlyaGusev/summarus/blob/master/summarus/tests/configs/ria_pgn.json#L51) and with your reader type will suffice.

If you'd like to use byte-pair encoding, run [train_subword_model.py](https://github.com/IlyaGusev/summarus#train_subword_modelpy) first to get BPE model. Then you should use the [SubwordTokenzier](https://github.com/IlyaGusev/summarus/blob/master/summarus/subword_tokenizer.py) in the reader config and the path to the BPE model as one of the fields of this config.

Third, you should run [train.py](https://github.com/IlyaGusev/summarus#trainpy) with defined model configuration.
Configuration examples: https://github.com/IlyaGusev/summarus/tree/master/summarus/tests/configs

**Comment by loongriver** [comment]
ok,i'll try
