### ISSUE TITLE
How to get more predicted headlines for reference?

### ISSUE THREAD

**Issue by AlfredAM** [IlyaGusev/summarus#10]
@IlyaGusev 
Hi there, thank you for your great work and explanation. Here's a quick question, how to get more predicted headlines, not only the best one, but also a few sub optimal ones, for reference. 

Thanks in advance.

**Comment by IlyaGusev** [comment]
Hi! You should use a custom predictor to get other samples from beam search.

Here is an example: https://colab.research.google.com/drive/1HfzPep7Thd3y7ztKYcbsBQuzV4NgH0PZ

**Comment by AlfredAM** [comment]
Hi! I tried BeamSubwordsSummaryPredictor with beam_size being 5, 10, 3, respectively, however, each time there's only 1 prediction in the output. 
I didn't retrain the generation model after adding the new predictor, does it need to be trained again? 
Thanks.

**Comment by IlyaGusev** [comment]
Did you pull last commits? There was an issue with PGN, and it was fixed in [ae60797](https://github.com/IlyaGusev/summarus/commit/ae60797f795db9a2dcc65d9e2959e59b5a5ac8b8).
No retraining is needed.

**Comment by AlfredAM** [comment]
Will do. Thanks for your quick response!

**Comment by AlfredAM** [comment]
Problem is resolved. Thanks a lot!
