### ISSUE TITLE
Can I use this model as is for CNNDM? 

### ISSUE THREAD

**Issue by Shashi456** [IlyaGusev/summarus#3]
I really like the implementation, for its conciseness and neat code. Can I use this as is for CNN daily mail, or how could I go about doing that, or say I want to use the PG in a pipeline and I have some text, how could I arrange this model?

**Comment by IlyaGusev** [comment]
You should write a reader for a dataset to apply models. As for CNN/DM dataset, it already has its own [reader](https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/cnn_dailymail_reader.py) and trained model:
https://www.dropbox.com/s/eay5b72cfr66atp/cnndm_20kk_words_pgn.tar.gz

To evaluate this model you should provide your own paths to cnn_stories_tokenized and dm_stories_tokenized in config.json. These directories can be found here: https://github.com/JafferWilson/Process-Data-of-CNN-DailyMail
As for test-path option for evaluate.py you should use url lists from here: https://github.com/abisee/cnn-dailymail/tree/master/url_lists

Command for train: `python3.6 train.py --train-path <path to all_train.txt> --model-path <path to model directory> --val-path <path to all_val.txt>`
Command for evaluation: `python evaluate.py --test-path <path to all_test.txt> --model-path <path to model directory> --metric rouge --report-every 100000 --batch-size 32 --is-multiple-ref`

Current ROUGE for PG without coverage loss:  {'rouge-1': {'f': 0.37650144404418406, 'p': 0.4617458063405975, 'r': 0.3365933007525164}, 'rouge-2': {'f': 0.16492728987357308, 'p': 0.20817063446768344, 'r': 0.147009800363632}, 'rouge-l': {'f': 0.32173469319332976, 'p': 0.42675868100413467, 'r': 0.3105522519507637}}

I hope this would help you :)

**Comment by Shashi456** [comment]
What about with coverage ? Have you tried your on model on with coverage?

**Comment by IlyaGusev** [comment]
Yeah, I have tried a bunch of models with coverage, but none of them achieves a better score than vanilla PG on this dataset. I suppose the problem is an incorrect implementation of coverage loss, though I didn't find any bugs in this part for a moment. Another reason for the strange behavior can be optimization settings that differ from the original ones.
