### ISSUE TITLE
could you please provide a guide of how to run copynet model with command？

### ISSUE THREAD

**Issue by zxr445116086** [IlyaGusev/summarus#4]
I can find the copynet implementation, but I can not find the command to actually use this copynet model.

Maybe you could provide some run script, maybe some run command, that I can run and test the model performance.

**Comment by zxr445116086** [comment]
some command I can just run the code, to test the performance

**Comment by IlyaGusev** [comment]
Hi!
If you want to test existing models for Russian news, you should download and unpack models stated here:
https://github.com/IlyaGusev/summarus#models
Every model directory contains a config file (usually config.json). The model type is stated in this file. For CopyNet, it will be "custom_copynet_seq2seq".
To test the performance of the existing model, you should use evaluate.py: https://github.com/IlyaGusev/summarus#evaluatepy

If you want to train your own model using CopyNet, you should create a clean directory, put there a config file with model.type="custom_copynet_seq2seq" (example: https://github.com/IlyaGusev/summarus/blob/master/summarus/tests/configs/cnn_dm_copynet.json#L3). Then run preprocess.py to create a vocabulary and train.py to train your model. If you want to use your own dataset for training, you should write a custom dataset reader, like this: https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/ria_reader.py

In case you have any questions or troubles, I'll be glad to help you :)

**Comment by zxr445116086** [comment]
> Hi!
> If you want to test existing models for Russian news, you should download and unpack models stated here:
> https://github.com/IlyaGusev/summarus#models
> Every model directory contains a config file (usually config.json). The model type is stated in this file. For CopyNet, it is "custom_copynet_seq2seq".
> To test the performance of the existing model, you should use evaluate.py: https://github.com/IlyaGusev/summarus#evaluatepy
> 
> If you want to train your own model using CopyNet, you should create a clean directory, put there a config file with model.type="custom_copynet_seq2seq" (example: https://github.com/IlyaGusev/summarus/blob/master/summarus/tests/configs/cnn_dm_copynet.json#L3). Then run preprocess.py to create a vocabulary and train.py to train your model. If you want to use your own dataset for training, you should write a custom dataset reader, like this: https://github.com/IlyaGusev/summarus/blob/master/summarus/readers/ria_reader.py
> 
> In case you have any questions or troubles, I'll be glad to help you :)

Hi, Ilya Gusev,
Thank you for your helpful guidance!  I will try to follow the setting.

I think if you can provide some command in the README file, so we can just run script and get the data download, preprocess, training, evaluation process to go, that will be great!
