### ISSUE TITLE
evaluation result on your models

### ISSUE THREAD

**Issue by y1041** [IlyaGusev/summarus#5]
Hello,
Thanks for your nice work. It's are clear.
but I have a question:
the models (copynet-bpe-43m, copynet-words-10m, ...) seem not performing well on my machine.
I used the model and config file you uploaded [here](https://www.dropbox.com/s/w67dcqf1mlv66uy/ria_43kk_subwords_copynet_short_context.tar.gz) and test "ria.shuffle.test.json"
but got bad result as below:
![image](https://user-images.githubusercontent.com/62011368/76298579-a3ed4680-62f4-11ea-80a0-999675bef2c5.png)
Rouge-1/2/L are all lower than even 5.
Do you have any idea what's wrong with my situation?

**Comment by IlyaGusev** [comment]
Sorry for a late answer.

It seems that it is a problem with tokenization as there are no spaces in the generated sentences. 
Probably you used a wrong predictor (word predictor for a subword-level model or vise versa).
It would be useful if you provide additional details.
