### ISSUE TITLE
Using mBart to summarize paragraph of other language

### ISSUE THREAD

**Issue by Luvata** [IlyaGusev/summarus#7]
Thank you for publishing your research and pretrained models

I saw that you finetuned `mBart` on `gazeta` dataset for summarization task in Russian. Since mBart is a multilingual model, I wonder if it could perform summarization on another language (kind of zero-shot summarization :D) ?

**Comment by IlyaGusev** [comment]
Hello!
mBART was trained for 25 languages. If your target language is one of them, you can fine-tune mBART for its summarization. It won't work in a zero-shot setup. I think it requires at least hundreds of examples to train properly.

**Comment by Luvata** [comment]
Thank you for your suggestion
