### ISSUE TITLE
Config file for train

### ISSUE THREAD

**Issue by AlfredAM** [IlyaGusev/summarus#9]
@IlyaGusev 
Thank you for your implementation sharing. 
Trying to train a model from scratch, but I keep getting the following error or some other error like that. e.g. "key 'data_loader' is required", etc. 

Traceback (most recent call last):
  File "/root/anaconda3/envs/env/lib/python3.8/site-packages/allennlp/common/params.py", line 238, in pop
    value = self.params.pop(key)
KeyError: 'train_data_path'
allennlp.common.checks.ConfigurationError: key "train_data_path" is required

I use the command below to run train.sh:
./train.sh -c "./pgn_title/ria_pgn.json" -s "./output" -t "./data/train_data.json" -v "./data/validate_data.json"
 
I would appreciate it if you could provide an example config file for train, as well as the 'preprocess.py' you have mentioned in another reply.

**Comment by IlyaGusev** [comment]
Hello!

[Here](https://colab.research.google.com/drive/1gT72c9kVlQE0nExZAgHvyflTLQnHlLpv) is a full example for model training on the Gazeta dataset.

'preprocess.py' is not needed anymore, as the AllenNLP 'train' handles vocabulary building itself.
